/* `components/index.js` ia a 'central export' for our components. */

export {default as Lander} from './Lander'
export {default as Footer} from './Footer'
export {default as Contact} from './Contact'
export {default as Events} from './Events'
export {default as About} from './About'
export {default as Scholarships} from './Scholarships'
export {default as Donations} from './Donations'
export {default as Photos} from './Photos'
export {default as Confirmation} from './Confirmation'
export {default as Error} from './Error'
export {default as Four04} from './Four04'
export {default as GridGallery} from './Gallery'
export {default as Construction} from './Construction'
export {default as HorseRacingInformation} from './HorseRacingInformation'
